package ar.com.abc.ventas.igu;

/**
 * Interfaz Gr�fica del Usuario Para el sistema
 * Ventas De Libros
 * @author  Marcelo Samia
 */

import java.awt.Color;
import java.io.IOException;
import java.util.logging.FileHandler;
import java.util.logging.Handler;
import java.util.logging.LogRecord;
import java.util.logging.Logger;

import javax.swing.UIManager;
import javax.swing.border.TitledBorder;

import ar.com.abc.ventas.Cliente;
import ar.com.abc.ventas.IControladorClientes;
import ar.com.abc.ventas.IModeloClientes;

public class IguVentas extends javax.swing.JFrame implements IguServicioDeRegistro {

  /**
   * 
   */
  private static final long serialVersionUID = 8479935778253317347L;
  private String nombreDelRegistro = "Aplicaci�n Para Venta De Libros";
  private Logger registrador = Logger.getLogger(nombreDelRegistro);
  private IPanelesDeVentas[] paneles = new IPanelesDeVentas[10];

  private IModeloClientes modelo;

  public void setModelo(IModeloClientes modelo) {
    this.modelo = modelo;
    // * C�digo para crear y a�adir el panel de cliente al vector de paneles.
    paneles[0] = panelDeClientes;
    paneles[0].registrarModelo(this.modelo);
    // * C�digo para panelDeTodosLosClientes
    paneles[1] = panelDeTodosLosClientes;
    paneles[1].registrarModelo(this.modelo);
  }

  public IguVentas() {
    initComponents();
    registrador.addHandler(new IguManejadorDeRegistro(this));
    try {
      registrador.addHandler(new FileHandler("Registro"));
    } catch (SecurityException | IOException e) {
      e.printStackTrace();
    }
  }

  public void agregarControlador(IControladorClientes controlador) {
    for (int i = 0; paneles[i] != null; i++)
      paneles[i].registrarControlador(controlador);
  }

  public void mostrarEnLaPantallaElObjeto(Object obj) {
    if (obj == null) {
      System.out.println("El objeto que se intenta mostrar es nulo.");
      return;
    }
    if (obj instanceof Cliente) {
      paneles[0].mostrar(obj);
      paneles[1].refrescar();
    }
    if (obj instanceof Cliente[]) {
      paneles[1].mostrar(obj);
    }
    if (obj instanceof Exception) {
      // registrar la excepci�n
      registrador.severe(obj.toString());
    }
  }

  public void setRegistro(String registro) {
    taRegistro.setText(registro);
  }

  public void agregarAlRegistro(String nuevoEventoDeRegistro) {
    taRegistro.append(nuevoEventoDeRegistro);
  }

  public class IguManejadorDeRegistro extends Handler {

    String registroDeMensajes = new String("");
    IguServicioDeRegistro mostrarRegistro;
    java.text.DateFormat df = java.text.DateFormat.getDateTimeInstance();

    public IguManejadorDeRegistro(IguServicioDeRegistro servicio) {
      mostrarRegistro = servicio;
    }

    public void publish(LogRecord registro) {
      // ** 1 Dar formato al registro y publicarlo usando el objeto
      // ** la instancia mostrarRegistro de IguServicioDeRegistro
      java.util.Date date = new java.util.Date(registro.getMillis());
      String dateString = df.format(date);
      registroDeMensajes = registro.getSequenceNumber() + " " +
          dateString + " " +
          registro.getLevel() + "\n" +
          registro.getMessage() + "\n" +
          registro.getSourceClassName() + " " +
          registro.getSourceMethodName() + "\n";
      if (registro.getSequenceNumber() == 0) {
        mostrarRegistro.setRegistro(registroDeMensajes);
      } else {
        mostrarRegistro.agregarAlRegistro(registroDeMensajes);
      }
    }

    public void flush() {
    }

    public void close() {
      registroDeMensajes = null;
    }
  }

  /**
   * This method is called from within the constructor to
   * initialize the form.
   * WARNING: Do NOT modify this code. The content of this method is
   * always regenerated by the Form Editor.
   */
  // <editor-fold defaultstate="collapsed" desc=" Generated Code
  // ">//GEN-BEGIN:initComponents
  private void initComponents() {
    jpManejoDeClientes = new javax.swing.JPanel();
    jtpClientes = new javax.swing.JTabbedPane();
    panelDeClientes = new ar.com.abc.ventas.igu.PanelDelCliente();
    panelDeTodosLosClientes = new ar.com.abc.ventas.igu.PanelDeLaTablaDeTodosLosClientes();
    panelDelRegistro = new javax.swing.JPanel();
    jspRegistro = new javax.swing.JScrollPane();
    taRegistro = new javax.swing.JTextArea();

    setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
    setTitle("Venta De Libros");
    jpManejoDeClientes.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
    jtpClientes.addTab("Detalles Del Cliente", panelDeClientes);

    jtpClientes.addTab("Todos Los Clientes", panelDeTodosLosClientes);

    javax.swing.GroupLayout gl_jpManejoDeClientes = new javax.swing.GroupLayout(jpManejoDeClientes);
    jpManejoDeClientes.setLayout(gl_jpManejoDeClientes);
    gl_jpManejoDeClientes.setHorizontalGroup(
        gl_jpManejoDeClientes.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jtpClientes, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE,
                404, Short.MAX_VALUE));
    gl_jpManejoDeClientes.setVerticalGroup(
        gl_jpManejoDeClientes.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jtpClientes, javax.swing.GroupLayout.DEFAULT_SIZE, 202, Short.MAX_VALUE));

    panelDelRegistro.setBorder(new TitledBorder(UIManager.getBorder("TitledBorder.border"), "Panel Del Registro",
        TitledBorder.LEADING, TitledBorder.TOP, null, new Color(0, 0, 0)));
    taRegistro.setColumns(20);
    taRegistro.setRows(5);
    jspRegistro.setViewportView(taRegistro);

    javax.swing.GroupLayout gl_panelDelRegistro = new javax.swing.GroupLayout(panelDelRegistro);
    panelDelRegistro.setLayout(gl_panelDelRegistro);
    gl_panelDelRegistro.setHorizontalGroup(
        gl_panelDelRegistro.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(gl_panelDelRegistro.createSequentialGroup()
                .addContainerGap()
                .addComponent(jspRegistro, javax.swing.GroupLayout.DEFAULT_SIZE, 372, Short.MAX_VALUE)
                .addContainerGap()));
    gl_panelDelRegistro.setVerticalGroup(
        gl_panelDelRegistro.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(gl_panelDelRegistro.createSequentialGroup()
                .addComponent(jspRegistro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE,
                    javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(17, Short.MAX_VALUE)));

    javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
    getContentPane().setLayout(layout);
    layout.setHorizontalGroup(
        layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jpManejoDeClientes, javax.swing.GroupLayout.DEFAULT_SIZE,
                javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(panelDelRegistro, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE,
                Short.MAX_VALUE));
    layout.setVerticalGroup(
        layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jpManejoDeClientes, javax.swing.GroupLayout.PREFERRED_SIZE,
                    javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(panelDelRegistro, javax.swing.GroupLayout.DEFAULT_SIZE,
                    javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)));
    pack();
  }// </editor-fold>//GEN-END:initComponents

  // Variables declaration - do not modify//GEN-BEGIN:variables
  private ar.com.abc.ventas.igu.PanelDeLaTablaDeTodosLosClientes panelDeTodosLosClientes;
  private ar.com.abc.ventas.igu.PanelDelCliente panelDeClientes;
  private javax.swing.JPanel jpManejoDeClientes;
  private javax.swing.JPanel panelDelRegistro;
  private javax.swing.JScrollPane jspRegistro;
  private javax.swing.JTabbedPane jtpClientes;
  private javax.swing.JTextArea taRegistro;
  // End of variables declaration//GEN-END:variables
}