package ar.com.abc.ventas.igu;

import javax.swing.GroupLayout;
import javax.swing.GroupLayout.Alignment;
import javax.swing.LayoutStyle.ComponentPlacement;
/*
 * PanelDelCliente.java
 *
 * Created on December 11, 2006, 2:38 PM
 */

import ar.com.abc.ventas.Cliente;
import ar.com.abc.ventas.IControladorClientes;
import ar.com.abc.ventas.IModeloClientes;

/**
 *
 * @author Marcelo Samia
 */
public class PanelDelCliente extends javax.swing.JPanel implements IPanelesDeVentas {
	/**
	 * 
	 */
	private static final long serialVersionUID = -7408641067093930131L;
	IModeloClientes modelo;
	IControladorClientes controlador;
	String dniCliente, nomCliente, dirCliente;

	public PanelDelCliente() {
		initComponents();
	}

	public void registrarControlador(IControladorClientes controlador) {
		this.controlador = controlador;
	}

	public void registrarModelo(IModeloClientes modelo) {
		this.modelo = modelo;
	}

	public void refrescar() {
		// Obtener el dni del Textfield
		try {
			// (Si no est� en blanco) conseguir el correspondiente objeto de cliente
			// del modelo para mostrar los detalles del cliente en el panel
			if (tfDni.getText().trim() != "") {
				// ** 1 Obtener el objeto del cliente correspondiente a tfDni
				// en el modelo y asigna a cliente.
				Cliente cliente = modelo.obtenerCliente((tfDni.getText()));
				// ** 2 Actualizar tfDireccion con el valor en cliente
				tfDireccion.setText(cliente.getDireccion());
				// ** 3 Actualizar tfNombre con el valor en cliente
				tfNombre.setText(cliente.getNombre());
			}
		} catch (Exception e) {
			System.out.println(e);
		}
	}

	public void mostrar(Object obj) {
		Cliente cliente;
		if (obj instanceof Cliente) {
			cliente = (Cliente) obj;
			dniCliente = tfDni.getText().trim();
			// Si cliente.getDni() es igual al dni del Cliente en PanelDelCliente
			// mostrar� el objeto del tipo Cliente en el PanelDelCliente
			if (dniCliente.equals(cliente.getDni())) {
				tfDireccion.setText(cliente.getDireccion());
				tfNombre.setText(cliente.getNombre());
			}
		}
	}

	public javax.swing.JPanel getPanel() {
		return this;
	}

	// M�todos de ayuda
	protected String getDniCliente() {
		return tfDni.getText().trim();
	}

	protected String getNombreCliente() {
		return tfNombre.getText().trim();
	}

	protected String getDireccionCliente() {
		return tfDireccion.getText().trim();
	}

	/**
	 * This method is called from within the constructor to
	 * initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is
	 * always regenerated by the Form Editor.
	 */
	// <editor-fold defaultstate="collapsed" desc=" Generated Code
	// ">//GEN-BEGIN:initComponents
	private void initComponents() {
		lblNombre = new javax.swing.JLabel();
		lblDni = new javax.swing.JLabel();
		lblDireccion = new javax.swing.JLabel();
		tfNombre = new javax.swing.JTextField();
		tfDni = new javax.swing.JTextField();
		tfDireccion = new javax.swing.JTextField();
		javax.swing.JButton btObtener = new javax.swing.JButton();
		btActualizar = new javax.swing.JButton();
		btAgregar = new javax.swing.JButton();
		btBorrar = new javax.swing.JButton();

		lblNombre.setText("Nombre del Cliente:");

		lblDni.setText("DNI del Cliente:");

		lblDireccion.setText("Direcci\u00F3n del Cliente:");

		btObtener.setText("Obtener Cliente");
		btObtener.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				btObtenerActionPerformed(evt);
			}
		});

		btActualizar.setText("Actualizar Cliente");
		btActualizar.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				btActualizarActionPerformed(evt);
			}
		});

		btAgregar.setText("Agregar Cliente");
		btAgregar.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				btAgregarActionPerformed(evt);
			}
		});

		btBorrar.setText("Borrar Cliente");
		btBorrar.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				btBorrarActionPerformed(evt);
			}
		});

		GroupLayout layout = new GroupLayout(this);
		layout.setHorizontalGroup(
				layout.createParallelGroup(Alignment.LEADING)
						.addGroup(layout.createSequentialGroup()
								.addContainerGap()
								.addGroup(layout.createParallelGroup(Alignment.LEADING)
										.addGroup(layout.createSequentialGroup()
												.addGroup(layout.createParallelGroup(Alignment.LEADING)
														.addComponent(btObtener, GroupLayout.DEFAULT_SIZE, 217, Short.MAX_VALUE)
														.addComponent(btAgregar, GroupLayout.DEFAULT_SIZE, 217, Short.MAX_VALUE))
												.addPreferredGap(ComponentPlacement.RELATED)
												.addGroup(layout.createParallelGroup(Alignment.LEADING)
														.addComponent(btBorrar, GroupLayout.DEFAULT_SIZE, 207, Short.MAX_VALUE)
														.addComponent(btActualizar, GroupLayout.DEFAULT_SIZE, 207, Short.MAX_VALUE)))
										.addGroup(Alignment.TRAILING, layout.createSequentialGroup()
												.addGroup(layout.createParallelGroup(Alignment.LEADING)
														.addGroup(layout.createSequentialGroup()
																.addComponent(lblDireccion, GroupLayout.DEFAULT_SIZE, 220, Short.MAX_VALUE)
																.addPreferredGap(ComponentPlacement.RELATED))
														.addComponent(lblNombre, GroupLayout.DEFAULT_SIZE, 224, Short.MAX_VALUE)
														.addComponent(lblDni, GroupLayout.DEFAULT_SIZE, 224, Short.MAX_VALUE))
												.addGroup(layout.createParallelGroup(Alignment.LEADING)
														.addComponent(tfDni, Alignment.TRAILING, GroupLayout.DEFAULT_SIZE, 206, Short.MAX_VALUE)
														.addComponent(tfDireccion, Alignment.TRAILING, GroupLayout.DEFAULT_SIZE, 206,
																Short.MAX_VALUE)
														.addComponent(tfNombre, Alignment.TRAILING, GroupLayout.DEFAULT_SIZE, 206,
																Short.MAX_VALUE))))
								.addContainerGap()));
		layout.setVerticalGroup(
				layout.createParallelGroup(Alignment.TRAILING)
						.addGroup(layout.createSequentialGroup()
								.addContainerGap()
								.addGroup(layout.createParallelGroup(Alignment.LEADING)
										.addGroup(layout.createSequentialGroup()
												.addComponent(tfNombre, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE,
														GroupLayout.PREFERRED_SIZE)
												.addPreferredGap(ComponentPlacement.RELATED)
												.addGroup(layout.createParallelGroup(Alignment.BASELINE)
														.addComponent(tfDni, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE,
																GroupLayout.PREFERRED_SIZE)
														.addComponent(lblDni)))
										.addComponent(lblNombre))
								.addPreferredGap(ComponentPlacement.RELATED)
								.addGroup(layout.createParallelGroup(Alignment.TRAILING)
										.addComponent(lblDireccion)
										.addComponent(tfDireccion, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE,
												GroupLayout.PREFERRED_SIZE))
								.addPreferredGap(ComponentPlacement.RELATED, 154, Short.MAX_VALUE)
								.addGroup(layout.createParallelGroup(Alignment.BASELINE)
										.addComponent(btObtener)
										.addComponent(btActualizar))
								.addPreferredGap(ComponentPlacement.RELATED)
								.addGroup(layout.createParallelGroup(Alignment.BASELINE)
										.addComponent(btBorrar)
										.addComponent(btAgregar))
								.addContainerGap()));
		this.setLayout(layout);
	}// </editor-fold>//GEN-END:initComponents

	private void btBorrarActionPerformed(java.awt.event.ActionEvent evt) {
		String nomBoton = evt.getActionCommand();
		dniCliente = getDniCliente();
		Cliente cliente = new Cliente(dniCliente, getNombreCliente(), getDireccionCliente());
		System.out.println("Oyente del Cliente. Bot�n = " + nomBoton);
		controlador.manejadorAccionBorrarCliente(cliente);
	}

	private void btActualizarActionPerformed(java.awt.event.ActionEvent evt) {
		String nomBoton = evt.getActionCommand();
		dniCliente = getDniCliente();
		Cliente cliente = new Cliente(dniCliente, getNombreCliente(), getDireccionCliente());
		System.out.println("Oyente del Cliente. Bot�n = " + nomBoton);
		controlador.manejadorAccionAcualizarCliente(cliente);
	}

	private void btAgregarActionPerformed(java.awt.event.ActionEvent evt) {
		String nomBoton = evt.getActionCommand();
		dniCliente = getDniCliente();
		Cliente cliente = new Cliente(dniCliente, getNombreCliente(), getDireccionCliente());
		System.out.println("Oyente del Cliente. Bot�n = " + nomBoton);
		controlador.manejadorAccionAgregarCliente(cliente);
	}

	private void btObtenerActionPerformed(java.awt.event.ActionEvent evt) {
		String nomBoton = evt.getActionCommand();
		dniCliente = tfDni.getText().trim();
		System.out.println("Oyente del Cliente. Bot�n = " + nomBoton);
		controlador.manejadorAccionObtenerCliente(dniCliente);
	}

	// Variables declaration - do not modify//GEN-BEGIN:variables
	private javax.swing.JButton btAgregar;
	private javax.swing.JLabel lblDireccion;
	private javax.swing.JTextField tfDireccion;
	private javax.swing.JButton btBorrar;
	private javax.swing.JLabel lblDni;
	private javax.swing.JTextField tfDni;
	private javax.swing.JLabel lblNombre;
	private javax.swing.JTextField tfNombre;
	private javax.swing.JButton btActualizar;
	// End of variables declaration//GEN-END:variables

}